"StatInfo"
{
    "modID"             "0a545b9a80b2c06512e7bf3d8a9bbae6"
    "schemaID"          "HED36L7LXTHQ5MPQ"
    "customSchema"      "schema"

    // Do we need to enable the round API or not.
    "HasRounds"         "false"

     // Do we want statCollection to use team winner for game victory?
    "GameWinner"        "true"

    // Do we want statCollection to use ancient explosions for game victory?
    "AncientExplosion"  "false"
}
